name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy api.rocket.rs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        with:
          key: build-cache
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            _build/
            _rocket/
      - name: Install Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: Build Docs
        run: ./build.sh
      # - name: Publish
      #   uses: cloudflare/pages-action@1
      #   with:
      #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #     projectName: api-rocket-rs
      #     directory: _output
      #     gitHubToken: ${{ secrets.GITHUB_TOKEN }}
